In [1]:
import numpy as np

<h2> Вправа № 1</h2>

In [8]:
n = 5
a = np.arange(1, n + 1)
np.diag(a)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

<h2>Вправа № 3</h2>

In [37]:
n = 6
m = 7
r = 2
c = 3
a = np.arange(n==0, m, +1)
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6]])

<h2> Вправа № 4</h2>

In [50]:
n = 3
m = 4
a = np.arange(0, m - 1)
np.diag(a)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

<h2> Вправа № 5</h2>

In [57]:
n = 5
a = np.arange(1, n)
np.diag(a)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

<h2> Вправа № 10</h2>

In [60]:
n  = 4
m = 5
a = np.random.random((n, m))
np.diag(a)

array([0.23066907, 0.20692673, 0.29201103, 0.9757402 ])

<h2> Вправа № 12 </h2>

In [63]:
n = 4
a = np.arange(0, n + n)
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 0, 7]])

<h2> Вправа № 16</h2>

In [68]:
n = 10
n = [int(x) for x in input().split()]
n = np.array(n)
n[n == 0] = -1
n

1 2 3 4 5 6 7 8 9 10


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h2>Вправа № 17</h2>

In [71]:
n = input().split()
result = []
for i in n:
    result.append(-1) if i == "0" else result.append(i)
result

1 2 3 4 5 6 7 8 9 10


['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [72]:
n = [int(x) for x in input().split()]
n = np.array(n)
n[n == 0] = -1
n

1 2 3 4 5 6 7 8 9 10


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h2>Вправа № 21</h2>

In [84]:
n = 4
m = 10
a = np.random.random((1, n + n))
np.diag(a)

array([0.02348601])

<h2> Завдання 2 - 3 ( Варіант № 8 )  </h2>

In [1]:
import numpy as np
import timeit
x = range(3)
x = np.random.standard_normal(3)
def pure_sum():
    return sum(x)
def numpy_sum():
    return np.sum(x)
n = 8
t1 = timeit.timeit(pure_sum, number = n)
print ('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = n)
print ('Numpy Sum:', t2)


Pure Python Sum: 5.420000525191426e-05
Numpy Sum: 0.0002221990143880248
